export interface ConceptEntry {
  cues: string[];
  terms: string[];
}

// A small deterministic safety net for common English/Hindi Ayurvedic concepts.
// AI query interpretation expands beyond this list when Vercel AI Gateway is available.
export const CONCEPTS: ConceptEntry[] = [
  { cues: ["health", "healthy", "wellbeing", "well-being", "स्वास्थ्य", "सेहत", "आरोग्य"], terms: ["ārogya", "svastha", "svasthya"] },
  { cues: ["disease", "illness", "sick", "रोग", "बीमारी"], terms: ["roga", "vyādhi", "ātura"] },
  { cues: ["long life", "longevity", "lifespan", "दीर्घायु", "लंबी आयु"], terms: ["dīrghajīvita", "dīrghāyu", "āyuṣ"] },
  { cues: ["life", "जीवन", "आयु"], terms: ["jīvita", "āyuṣ"] },
  { cues: ["destroy", "destroyer", "destruction", "विनाश", "नाशक"], terms: ["apahartṛ", "vināśa", "nāśa"] },
  { cues: ["foundation", "root", "basis", "मूल", "आधार"], terms: ["mūla"] },
  { cues: ["four goals", "goals of life", "purpose of life", "पुरुषार्थ"], terms: ["dharma", "artha", "kāma", "mokṣa"] },
  { cues: ["three doshas", "tridosha", "तीन दोष", "त्रिदोष"], terms: ["vāta", "pitta", "kapha"] },
  { cues: ["vata", "वात", "वायु"], terms: ["vāta", "vāyu"] },
  { cues: ["pitta", "पित्त"], terms: ["pitta"] },
  { cues: ["kapha", "कफ"], terms: ["kapha", "śleṣman"] },
  { cues: ["digestion", "digestive fire", "metabolism", "पाचन", "अग्नि"], terms: ["agni", "jāṭharāgni", "pācana"] },
  { cues: ["food", "diet", "meal", "भोजन", "आहार"], terms: ["āhāra", "anna", "bhojana"] },
  { cues: ["sleep", "नींद", "निद्रा"], terms: ["nidrā", "svapna"] },
  { cues: ["celibacy", "brahmacharya", "ब्रह्मचर्य"], terms: ["brahmacarya"] },
  { cues: ["pillars of life", "three pillars", "उपस्तम्भ", "जीवन के स्तंभ"], terms: ["upastambha", "āhāra", "svapna", "brahmacarya"] },
  { cues: ["natural urges", "urge", "suppress urges", "वेग", "वेग धारण"], terms: ["vega", "dhāraṇa", "adhāraṇīya"] },
  { cues: ["physician", "doctor", "वैद्य", "चिकित्सक"], terms: ["vaidya", "bhiṣaj", "cikitsaka"] },
  { cues: ["medicine", "drug", "औषध", "दवा"], terms: ["auṣadha", "bheṣaja", "dravya"] },
  { cues: ["treatment", "therapy", "इलाज", "चिकित्सा"], terms: ["cikitsā", "upāya", "śamana"] },
  { cues: ["cause symptom treatment", "three principles", "त्रिसूत्र"], terms: ["hetu", "liṅga", "auṣadha", "trisūtra"] },
  { cues: ["cause", "etiology", "कारण", "हेतु"], terms: ["hetu", "nidāna"] },
  { cues: ["symptom", "sign", "लक्षण", "चिह्न"], terms: ["liṅga", "lakṣaṇa", "rūpa"] },
  { cues: ["similarity", "समानता", "सामान्य"], terms: ["sāmānya"] },
  { cues: ["difference", "dissimilarity", "विशेष", "असमानता"], terms: ["viśeṣa"] },
  { cues: ["taste", "रस", "स्वाद"], terms: ["rasa"] },
  { cues: ["six tastes", "छः रस", "षड्रस"], terms: ["ṣaḍrasa", "madhura", "amla", "lavaṇa", "kaṭu", "tikta", "kaṣāya"] },
  { cues: ["sweet taste", "मीठा", "मधुर"], terms: ["madhura", "rasa"] },
  { cues: ["incompatible food", "wrong food combination", "विरुद्ध आहार"], terms: ["viruddha", "āhāra"] },
  { cues: ["daily routine", "दिनचर्या", "daily regimen"], terms: ["dinacaryā", "nityam"] },
  { cues: ["seasonal routine", "ऋतुचर्या", "season"], terms: ["ṛtu", "ṛtucaryā"] },
  { cues: ["exercise", "व्यायाम"], terms: ["vyāyāma"] },
  { cues: ["water", "जल", "पानी"], terms: ["jala", "udaka", "ambu"] },
  { cues: ["milk", "दूध", "क्षीर"], terms: ["kṣīra", "dugdha"] },
  { cues: ["ghee", "घी", "घृत"], terms: ["ghṛta", "sarpiḥ"] },
  { cues: ["honey", "शहद", "मधु"], terms: ["madhu"] },
  { cues: ["fasting", "उपवास", "लङ्घन"], terms: ["laṅghana", "upavāsa"] },
  { cues: ["nourishing", "weight gain", "बृंहण", "पोषण"], terms: ["bṛṃhaṇa", "saṃtarpaṇa"] },
  { cues: ["obesity", "overweight", "मोटापा", "स्थूलता"], terms: ["atisthaulya", "sthūla", "medas"] },
  { cues: ["emaciation", "underweight", "कृशता"], terms: ["atikṛśa", "kṛśa"] },
  { cues: ["fever", "बुखार", "ज्वर"], terms: ["jvara"] },
  { cues: ["diabetes", "मधुमेह", "प्रमेह"], terms: ["madhumeha", "prameha"] },
  { cues: ["cough", "खाँसी", "कास"], terms: ["kāsa"] },
  { cues: ["asthma", "श्वास"], terms: ["śvāsa"] },
  { cues: ["skin disease", "त्वचा रोग", "कुष्ठ"], terms: ["kuṣṭha", "tvac"] },
  { cues: ["heart", "cardiac", "हृदय", "दिल"], terms: ["hṛdaya", "hṛdroga"] },
  { cues: ["mind", "mental", "मन", "मानसिक"], terms: ["manas", "sattva"] },
  { cues: ["memory", "स्मृति", "याददाश्त"], terms: ["smṛti", "medhā"] },
  { cues: ["pregnancy", "गर्भावस्था", "गर्भ"], terms: ["garbha", "garbhiṇī"] },
  { cues: ["child", "children", "बाल", "शिशु"], terms: ["bāla", "śiśu", "kumāra"] },
  { cues: ["old age", "aging", "वृद्धावस्था", "बुढ़ापा"], terms: ["jarā", "vṛddha"] },
  { cues: ["rejuvenation", "longevity therapy", "रसायन"], terms: ["rasāyana"] },
  { cues: ["aphrodisiac", "fertility", "वाजीकरण"], terms: ["vājīkaraṇa"] },
  { cues: ["emesis", "vomiting therapy", "वमन"], terms: ["vamana"] },
  { cues: ["purgation", "विरेचन"], terms: ["virecana"] },
  { cues: ["enema", "बस्ति", "बस्ती"], terms: ["basti"] },
  { cues: ["oil", "unctuous", "तेल", "स्नेह"], terms: ["sneha", "taila", "snigdha"] },
  { cues: ["sweating", "fomentation", "स्वेदन", "पसीना"], terms: ["sveda", "svedana"] },
  { cues: ["blood", "रक्त", "खून"], terms: ["rakta", "śoṇita"] },
  { cues: ["urine", "मूत्र"], terms: ["mūtra"] },
  { cues: ["stool", "feces", "मल"], terms: ["mala", "purīṣa"] },
  { cues: ["truth", "सत्य"], terms: ["satya"] },
  { cues: ["compassion", "करुणा", "दया"], terms: ["anukrośa", "dayā"] },
  { cues: ["all beings", "living beings", "सभी प्राणी", "सर्वभूत"], terms: ["sarvabhūta", "bhūta", "prāṇin"] },
  { cues: ["knowledge", "ज्ञान", "विद्या"], terms: ["jñāna", "vidyā"] },
  { cues: ["soul", "आत्मा"], terms: ["ātman", "puruṣa"] },
];
